var language_us = [
/*0*/'RCG',
/*1*/'Game description',
/*2*/'RCG is an open, transparent and fully automatic decentralized on-chain financial management game built on the Ethereum smart contract. Players located anywhere in the world can participate freely through imtoken 2.0 wallet! No individual or organization can control the operation of the system or control the funds in the system.',
/*3*/'Join now',
/*4*/'Participate',
/*5*/'Ticket',
/*6*/'Invite',
/*7*/'Rule',
/*8*/'Current burning ratio',
/*9*/'Send ETH',
/*10*/'Purchase admission tickets',
/*11*/'Buy',
/*12*/'My referee is',
/*13*/'My direct push quantity',
/*14*/'My invitation link',
/*15*/'Copy my invitation link',
/*16*/'Rules of play',
/*17*/'An account can only accept one investment before exiting, and can continue to invest after exiting',
/*18*/'Static dividends fluctuate from 0.3% to 2.2% per day',
/*19*/'Out of the game, according to 1-10 for the investment amount of 3 times, 11-20 for the investment amount of 4 times, greater than 21for the investment amount of 5 times',
/*20*/'Node sharing revenue 30% according to: 6% -5% -4% -3% -2% -2% -2% -2% -2% -2% -2%',
/*21*/'After the security contract reaches the specified time, the security contract no longer precipitates until the next round of account opening.',
/*22*/'After the sharing contract reaches the specified time, it will no longer be deposited, and the investment amount will directly enter the dividend income.',
/*23*/'The dynamic and static conditions did not meet the conditions, which precipitated to the sub-shared contract.',
/*24*/'Statistics',
/*25*/'My income',
/*26*/'Settled dividend income',
/*27*/'Node sharing revenue',
/*28*/'Revenue sharing',
/*29*/'Next income countdown',
/*30*/'-Income limit remains',
/*31*/'Unsettled income',
/*32*/'Settle',
/*33*/'Small prize pool',
/*34*/'withdraw',
/*35*/'Unwithdraw income',
/*36*/'Withdraw income',
/*37*/'statistics',
/*38*/'Sharing contract currently',
/*39*/'Small pot',
/*40*/'Ticket burnout rate',
/*41*/'Has been burned',
/*42*/'Total invested',
/*43*/'Total settled',
/*44*/'Total recommended',
/*45*/'Team',
/*46*/'Withdraw',
/*47*/'Ambassador',
/*48*/'Historical record',
/*49*/'Grand Prize Pool',
/*50*/'Little prize pool',
/*51*/'View my statistics',
/*52*/'Registered Sharer',
/*53*/'3% of the global player deposit amount enters the security contract. When the sharing contract is 0, the security contract function will be opened, and the last 1,000 players participating will be evenly distributed according to the investment amount..',
/*54*/'Current pool total',
/*55*/'Supernode income',
/*56*/'Available tokens',
/*57*/'Decentralized game system',
/*58*/'Smart ｜ No center ｜ 100% transparent',
/*59*/'Video introduction',
/*60*/'Participate in the game',
/*61*/'-Strategic partners- ',
/*62*/'',
]; 
var language_cn = [
/*0*/'RCG',
/*1*/'游戏介绍',
/*2*/'RCG是一款基于以太坊智能合约而构建的公开、透明、全自动运行去中心化链上理财游戏。位于全球任意位置的玩家，通过imtoken 2.0钱包即可自由参与！任何个人或机构都不能操控系统运行或掌控系统内的资金。',
/*3*/'立即参与',
/*4*/'参与',
/*5*/'令牌',
/*6*/'邀请',
/*7*/'规则',
/*8*/'当前消耗令牌比例',
/*9*/'发送ETH',
/*10*/'购买入场令牌',
/*11*/'购买',
/*12*/'我的分享人是',
/*13*/'我的分享人数',
/*14*/'我的邀请链接',
/*15*/'复制我的链接',
/*16*/'玩法与规则',
/*17*/'一个账户只投资一笔，出局后可复投',
/*18*/'静态分红按照每天0.3%～2.2%上下浮动',
/*19*/'动静出局，按照1-10为投投资的3倍，11-20为投资额的4倍，等于或大于21为投资额的5倍',
/*20*/'节点分享收益30%按照:6%-5%-4%-3%-2%-2%-2%-2%-2%-2%相应奖金，可即時提币',
/*21*/'保全合约达到指定时间后，保全合约不再沉淀，直到开户下一轮',
/*22*/'共享合约达到指定时间后，不再沉淀，投资额直接进入分红收益',
/*23*/'动静态未达到条件，沉淀至分共享合约',
/*24*/'数据统计',
/*25*/'我的收益',
/*26*/'已结算分红收益',
/*27*/'节点分享收益',
/*28*/'共享合约收益',
/*29*/'下次分红时间差',
/*30*/'动静出局还差',
/*31*/'未结算预计收益',
/*32*/'结算',
/*33*/'保全合约收益',
/*34*/'提现',
/*35*/'未提币数量',
/*36*/'提现收益',
/*37*/'当前统计',
/*38*/'共享合约当前总量',
/*39*/'RCG当前总量',
/*40*/'令牌焚毀倍率',
/*41*/'已焚毀令牌',
/*42*/'当前参与总量',
/*43*/'总已结算分红收益',
/*44*/'总的分享收益',
/*45*/'团队',
/*46*/'提币',
/*47*/'大使',
/*48*/'历史记录',
/*49*/'共享合约',
/*50*/'保全合约',
/*51*/'查看我的统计数据',
/*52*/'注册分享人',
/*53*/'全球玩家入金数量的3%进入保全合约，当共享合约为0的时候，就会开启保全合约功能，给最后参与的1000名玩家，按投资额平均分配。',
/*54*/'保全合约当前总量',
/*55*/'超级节点分红收益',
/*56*/'当前可用令牌',
/*57*/'去中心化链上游戏理财系统',
/*58*/'全自动｜无中心｜100%透明',
/*59*/'视频介绍',
/*60*/'参与游戏',
/*61*/'-战略伙伴- ',
/*62*/'',
];

var tipl_language_us = [
/*0*/'This is a test, please use the ropsten test network!',
/*1*/'Please use the official Ethereum main network!',
/*2*/"For Chrome, Firefox please download <a style='color:#fcd21c;font-size:18px;' href=' javascript:;'>metamask</a> or mobile phone download <a style='color:#fcd21c;font-size:18px;' href='javascript:;'>trustwallet</a> !",
/*3*/'Please login to Metamask or trustwallet!',
/*4*/'Please select the correct Ethernet network!',
/*5*/'Successful copy:',
/*6*/'Please enter the correct referrer',
/*7*/'The minimum investment amount is 1!',
/*8*/'Your total deposit must be greater than 1 before re-investment!',
/*9*/'The amount of your re-investment must be less than your total deposit amount!',
/*10*/'Your total deposit must be greater than 0.1 before it can be withdrawn!',
/*11*/'Your ticket is not enough ',
/*12*/'Invalid referrer, please confirm that the referrer has participated',
/*13*/'There are already recommenders',
/*14*/'Invalid referrer, please confirm that the referee is involved in the wealth journey',
/*15*/'You have been tied as a referrer and cannot register',
/*16*/'Your investment in the investment still has a profit, please wait for the income to be completed and then invest again!',
/*17*/'Data loading, please wait...',
/*18*/'Minimum purchase',
/*19*/'Please confirm that your input is correct',
/*20*/'Waiting',
/*21*/'Payment parameters are not loaded',
/*22*/'Purchase quantity is a multiple of 0.1 ETH',
/*23*/'Participation in multiples of 1ETH',
/*24*/"Can't invest without sharing people。",
/*25*/'Network is busy, please try again later。',
/*26*/'Business is processing, please try again later。',
/*27*/'Shared by invalid',
/*28*/'Invalid wallet address',
/*29*/'Failed to create investment account',
/*30*/'Transaction HASH is invalid',
/*31*/'Transaction sent successfully',
]; 
var tipl_language_cn = [
/*0*/'这是一个测试，请使用ropsten测试网！',
/*1*/'请使用正式以太坊主网！',
/*2*/"在Chrome、Firefox中使用请下载 <a style='color:#fcd21c;font-size:18px;' href='javascript:;'>metamask</a> 或 手机端下载 <a style='color:#fcd21c;font-size:18px;' href='javascript:;'>trustwallet</a> ！",
/*3*/'请先登录 Metamask 或 trustwallet！',
/*4*/'请选择正确的以太网络！',
/*5*/'复投成功：：',
/*6*/'请输入正确的分享人',
/*7*/'最小投资额为 1ETH',
/*8*/'您的余额必须大于 1ETH才可复投！',
/*9*/'参与数量必须大于或等于上次参与的数量！',
/*10*/'您的余额必须大于0.1ETH才可提现！',
/*11*/'您的令牌数量不足 ',
/*12*/'无效的分享人，请确认分享人已参与',
/*13*/'已经存在推荐人了',
/*14*/'无效的分享人，请确认分享人参与了投资',
/*15*/'您已经被绑定为分享人，无法注册',
/*16*/'您的上笔投资尚有收益，请等待收益完成后再次投资!',
/*17*/'数据加载中，请稍后...',
/*18*/'最小起购 0.1 ETH',
/*19*/'请确认您的输入是否正确',
/*20*/'等待下一轮',
/*21*/'支付参数未加载',
/*22*/'购买数量必须是0.1 ETH的倍数',
/*23*/'参与数量必须是 1ETH 的倍数',
/*24*/'没有分享人，无法投资。',
/*25*/'网络繁忙，请稍后再试。',
/*26*/'业务正在处理，请稍后再试。',
/*27*/'分享人无效',
/*28*/'钱包地址无效',
/*29*/'创建投资账户失败',
/*30*/'交易HASH无效',
/*31*/'交易发送成功',
];
